version: '3'

services:
  traefik:
    image: traefik:v2.10
    restart: always
    command:
      - "--api.insecure=false" # Désactive l'interface web en prod
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=ton_email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=web"
    ports:
      - "80:80"
      - "443:443"  # Ajout du port HTTPS
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./acme.json:/letsencrypt/acme.json"

  react-app:
    build: .
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-app.rule=Host(`nathan.soudry-ort.online`)"
      - "traefik.http.routers.react-app.entrypoints=websecure"
      - "traefik.http.routers.react-app.tls.certresolver=myresolver"
      - "traefik.http.services.react-app.loadbalancer.server.port=3000"
